// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cdStore.Data;

#nullable disable

namespace cdStore.Migrations
{
    [DbContext(typeof(CdContext))]
    [Migration("20220216095645_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("cdStore.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistOrigin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistId");

                    b.HasIndex("CdId");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("cdStore.Models.Cd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("CdName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cd");
                });

            modelBuilder.Entity("cdStore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CdUser", b =>
                {
                    b.Property<int>("CdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CdId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CdUser");
                });

            modelBuilder.Entity("cdStore.Models.Artist", b =>
                {
                    b.HasOne("cdStore.Models.Cd", "Cd")
                        .WithMany()
                        .HasForeignKey("CdId");

                    b.Navigation("Cd");
                });

            modelBuilder.Entity("CdUser", b =>
                {
                    b.HasOne("cdStore.Models.Cd", null)
                        .WithMany()
                        .HasForeignKey("CdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cdStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
